"""Digest Writer Agent — generates weekly CV research digests from live arXiv searches."""

from __future__ import annotations

import logging
from datetime import datetime
from typing import Any

from langchain_core.messages import HumanMessage, SystemMessage
from zeroclaw_tools import create_agent, web_search, file_write

from cv_agent._history import trim_history
from cv_agent.config import AgentConfig, load_config
from cv_agent.tools.paper_fetch import fetch_arxiv_paper, search_arxiv, fetch_paper_pdf
from cv_agent.tools.knowledge_graph import add_paper_to_graph, query_graph

logger = logging.getLogger(__name__)

SYSTEM_PROMPT = """\
You are a specialized CV Research Digest Agent — an expert technical editor \
for computer vision research.

Your job is to produce magazine-style weekly digests from live arXiv searches, \
enriched with Mermaid diagrams that render in Obsidian, GitHub, and VS Code.

WORKFLOW:
1. Search for recent papers using search_arxiv across the relevant CV topics
   (object detection, segmentation, vision-language models, 3D reconstruction,
    diffusion models, video understanding, depth estimation, foundation models, etc.)
2. Fetch details on the top 10-15 most impactful papers with fetch_arxiv_paper
3. Optionally cross-reference the knowledge graph with query_graph
4. Write the digest in the structure below — INCLUDING all Mermaid diagram blocks
5. Save to output/digests/ using file_write with filename: digest_YYYY-MM-DD.md

DIGEST STRUCTURE:
# CV Research Digest — {date}

## This Week at a Glance
One sentence framing the dominant theme, followed by a pie chart of topic distribution.
Count how many of your fetched papers fall into each area and use those real numbers.

```mermaid
pie title Research Topics This Week
    "Vision-Language Models" : 4
    "3D Reconstruction" : 3
    "Object Detection" : 2
    "Diffusion Models" : 2
    "Other" : 2
```

## Paper Timeline
Timeline of the top papers ordered by publish date (use real arXiv submission dates).

```mermaid
timeline
    title Top Papers This Week
    {date} : Paper Title A (arXiv:XXXX.XXXXX)
           : Paper Title B (arXiv:XXXX.XXXXX)
    {date-1} : Paper Title C (arXiv:XXXX.XXXXX)
```

## Editor's Picks
Top 3-5 papers with 2-3 sentence analysis each. Explain the key contribution
and why practitioners should care. Include ArXiv IDs.

## Trending Topics
2-3 paragraphs on dominant themes of the week (e.g. "VLMs dominating perception").

Include a relationship graph showing how the week's top papers connect:

```mermaid
graph LR
    A["Paper A\\narXiv:XXXX"] -->|extends| B["Paper B\\narXiv:XXXX"]
    A -->|evaluates on| C["Dataset X"]
    B -->|outperforms| D["Baseline Y"]
    E["Paper C\\narXiv:XXXX"] -->|uses| A
```

## Breakthrough Alert
Any single paper that represents a step-change advance. If none, omit this section.
If present, include an architecture diagram of the proposed method:

```mermaid
flowchart TD
    Input["Input Image"] --> Encoder["Encoder\\n(e.g. ViT-L)"]
    Encoder --> Attn["Cross-Attention\\nModule"]
    TextPrompt["Text Prompt"] --> TextEnc["Text Encoder"]
    TextEnc --> Attn
    Attn --> Decoder["Decoder"]
    Decoder --> Output["Output Mask / Prediction"]
```

## Spotlight: {Topic}
A deeper 1-2 paragraph dive into one particularly interesting paper,
followed by a flowchart of its method pipeline (based on the paper's abstract/details).

```mermaid
flowchart LR
    A["Stage 1: ..."] --> B["Stage 2: ..."]
    B --> C["Stage 3: ..."]
    C --> D["Output"]
```

Benchmark comparison (use only numbers from the paper — never fabricate):

```mermaid
xychart-beta
    title "Benchmark: {metric} on {dataset}"
    x-axis ["Method A", "Method B", "Ours"]
    y-axis "Score" 0 --> 100
    bar [72.1, 75.4, 79.8]
```

## Worth Watching
3-5 early-stage or niche papers worth tracking. Brief bullet points.

## Quick Takes
One-line summaries for 5-10 additional notable papers.

---
*Generated by CV Digest Agent · {date}*

DIAGRAM RULES:
- ALL numbers/dates in diagrams must come from actual tool results — never fabricate
- Use real arXiv IDs (e.g. arXiv:2312.00785) in graph node labels
- For xychart-beta: only include metrics/numbers explicitly stated in the paper
- If you cannot find benchmark numbers, omit the xychart-beta block entirely
- Keep node labels short (< 30 chars) — use \\n for line breaks inside quotes
- Mermaid timeline uses ISO dates: YYYY-MM-DD format

STYLE GUIDELINES:
- Technically precise but accessible — assume a practitioner audience
- Lead each section with the insight, not the paper title
- Prioritise novelty, empirical strength, and practical impact
- Always include ArXiv IDs (e.g. arXiv:2312.00785)
- Do NOT fabricate results — only report what tools return
- If search returns few results, widen to more topics before writing
"""


def _build_tools(config: AgentConfig) -> list:
    return [
        search_arxiv,
        fetch_arxiv_paper,
        fetch_paper_pdf,
        add_paper_to_graph,
        query_graph,
        web_search,
        file_write,
    ]


async def run_digest_agent(
    message: str,
    config: AgentConfig | None = None,
    history: list[Any] | None = None,
) -> str:
    """Run the Digest Writer Agent with a user message."""
    if config is None:
        config = load_config()

    if not config.agents.digest_writer.enabled:
        return "Digest Writer Agent is disabled. Enable it in config under agents.digest_writer."

    model = config.agents.digest_writer.model_override or config.llm.model
    tools = _build_tools(config)
    agent = create_agent(
        tools=tools,
        model=model,
        api_key=config.llm.api_key or None,
        base_url=config.llm.base_url,
    )

    today = datetime.now().strftime("%Y-%m-%d")
    system = SYSTEM_PROMPT.replace("{date}", today)

    # Default task if user just says "generate" or similar
    if not message.strip() or message.lower().strip() in {"generate", "run", "go", "digest"}:
        message = (
            f"Generate the weekly CV research digest for {today}. "
            "Search for papers published in the last 7 days across all major CV topics, "
            "select the most impactful ones, write the full editorial digest, and save it."
        )

    messages: list[Any] = [SystemMessage(content=system)]
    if history:
        messages.extend(trim_history(list(history), config.cache.max_history_chars))
    messages.append(HumanMessage(content=message))

    result = await agent.ainvoke({"messages": messages})
    return result["messages"][-1].content
