"""Weekly digest / magazine generator from research monitoring."""

from __future__ import annotations

import logging
from datetime import datetime
from pathlib import Path

import httpx

from cv_agent.config import AgentConfig, load_config
from cv_agent.research.monitor import ResearchMonitor
from cv_agent.research.sources import Paper

logger = logging.getLogger(__name__)


def _summarize_with_llm(papers_text: str, config: AgentConfig) -> str:
    """Use LLM to create an editorial summary of the week's papers."""
    base_url = config.llm.base_url.rstrip("/")

    prompt = (
        "You are a computer vision research editor writing a weekly digest. "
        "Create an engaging, informative magazine-style summary of this week's papers.\n\n"
        "Structure:\n"
        "1. **Editor's Picks** — Top 3-5 most impactful papers with brief analysis\n"
        "2. **Trending Topics** — What themes dominated this week\n"
        "3. **Breakthrough Alert** — Any papers that represent significant advances\n"
        "4. **Worth Watching** — Interesting but early-stage work\n"
        "5. **Quick Takes** — One-line summaries of remaining notable papers\n\n"
        "Write in an accessible but technically precise style. "
        "Include ArXiv IDs for reference.\n\n"
        f"This week's papers:\n\n{papers_text[:12000]}"
    )

    payload = {
        "model": config.llm.model,
        "messages": [{"role": "user", "content": prompt}],
        "temperature": 0.4,
        "max_tokens": config.llm.max_tokens,
    }
    headers = {}
    if config.llm.api_key:
        headers["Authorization"] = f"Bearer {config.llm.api_key}"

    with httpx.Client(timeout=180) as client:
        resp = client.post(f"{base_url}/chat/completions", json=payload, headers=headers)
        resp.raise_for_status()
        return resp.json()["choices"][0]["message"]["content"]


def _format_paper_entry(paper: Paper, index: int) -> str:
    """Format a single paper for the digest."""
    authors = ", ".join(paper.authors[:3])
    if len(paper.authors) > 3:
        authors += " et al."

    entry = (
        f"### {index}. {paper.title}\n"
        f"**Authors:** {authors}\n"
        f"**Source:** {paper.source} | **Date:** {paper.published}\n"
        f"**Link:** {paper.url}\n"
    )
    if paper.pdf_url:
        entry += f"**PDF:** {paper.pdf_url}\n"
    if paper.code_url:
        entry += f"**Code:** {paper.code_url}\n"
    if paper.citation_count > 0:
        entry += f"**Citations:** {paper.citation_count}\n"

    abstract = paper.abstract
    if len(abstract) > 400:
        abstract = abstract[:397] + "..."
    entry += f"\n> {abstract}\n"

    return entry


async def generate_weekly_digest(config: AgentConfig | None = None) -> str:
    """Generate the weekly CV research digest/magazine.

    Fetches new papers from all sources, groups by topic, and generates
    an LLM-summarized editorial digest.
    """
    if config is None:
        config = load_config()

    monitor = ResearchMonitor(config)
    now = datetime.now()
    date_str = now.strftime("%Y-%m-%d")
    week_str = now.strftime("Week %U, %Y")

    logger.info(f"Generating weekly digest for {week_str}")

    # Fetch papers
    papers = monitor.check_all_sources()
    if not papers:
        return f"# CV Research Digest — {week_str}\n\nNo new papers found this period."

    # Group by topic
    topics = monitor.get_papers_by_topic(papers)

    # Build the raw paper listing
    raw_parts = []
    paper_index = 1
    for topic, topic_papers in topics.items():
        raw_parts.append(f"\n## {topic}\n")
        for paper in topic_papers[:10]:  # Cap per topic
            raw_parts.append(_format_paper_entry(paper, paper_index))
            paper_index += 1

    raw_listing = "\n".join(raw_parts)

    # Generate editorial summary with LLM
    try:
        editorial = _summarize_with_llm(raw_listing, config)
    except Exception:
        logger.exception("LLM summary failed, using raw listing")
        editorial = "*LLM summary unavailable — raw listing below.*"

    # Assemble the full digest
    digest = (
        f"# 👁️ CV Research Weekly — {week_str}\n\n"
        f"*Generated: {date_str} | Papers found: {len(papers)}*\n\n"
        f"---\n\n"
        f"## Editorial Summary\n\n{editorial}\n\n"
        f"---\n\n"
        f"## Full Paper Listing\n\n{raw_listing}\n\n"
        f"---\n\n"
        f"*Generated by CV Zero Claw Agent*\n"
    )

    # Save to file
    output_dir = Path(config.output.digests_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    digest_path = output_dir / f"digest_{date_str}.md"
    digest_path.write_text(digest)

    logger.info(f"Digest saved to {digest_path}")
    return digest
